import completeness_sets_functions_nontrigonometric_harmonic_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace completeness_sets_functions_nontrigonometric_harmonic_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end completeness_sets_functions_nontrigonometric_harmonic_lemma_canonical_lane_mathlib
end HautevilleHouse
